#!/usr/bin/ruby

require_relative "lib/shell/shell.rb"
require_relative "lib/searchful/searchful.rb"


command = Shell::Parser::get_command ARGV

unless command.nil? || command.empty? then
  command_file = "lib/searchful/commands/" + command + ".rb"
  
  # checks if class file exists
  if File.exists? command_file then
    require_relative command_file
    command = command.capitalize
    command_obj = Searchful::Commands.const_get(command).new(ARGV)
    
  end
  
end